// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const processEnv = typeof process !== "undefined" ? process.env : {};
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || processEnv.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || processEnv.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    console.warn(`[Supabase] Missing environment variable(s): ${missing.join(", ")}. Auth and data features will be disabled.`);
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

type SupabaseClient = NonNullable<ReturnType<typeof createSupabaseClient>>;

let _supabase: SupabaseClient | null | undefined;

function getClient(): SupabaseClient {
  if (_supabase === undefined) _supabase = createSupabaseClient();
  if (!_supabase) {
    // Return a no-op proxy so callers don't crash when Supabase is not configured
    return new Proxy({} as SupabaseClient, {
      get(_, prop) {
        if (prop === "auth") {
          return new Proxy({} as SupabaseClient["auth"], {
            get(__, authProp) {
              if (authProp === "getSession") return async () => ({ data: { session: null }, error: null });
              if (authProp === "onAuthStateChange") return (_evt: unknown, _cb: unknown) => ({ data: { subscription: { unsubscribe: () => {} } } });
              if (authProp === "signUp") return async () => ({ data: { user: null, session: null }, error: { message: "Supabase not configured" } });
              if (authProp === "signInWithPassword") return async () => ({ data: { user: null, session: null }, error: { message: "Supabase not configured" } });
              if (authProp === "signOut") return async () => ({});
              if (authProp === "resetPasswordForEmail") return async () => ({ error: { message: "Supabase not configured" } });
              return async () => ({ data: null, error: { message: "Supabase not configured" } });
            },
          });
        }
        // For .from(), .channel(), etc. — return chainable no-ops
        return () => new Proxy({} as never, {
          get(__, p) {
            if (p === "then") return undefined; // not a Promise
            return () => new Proxy({} as never, {
              get(___, p2) {
                if (p2 === "then") return undefined;
                return () => Promise.resolve({ data: null, error: null });
              },
            });
          },
        });
      },
    });
  }
  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient, {
  get(_, prop, receiver) {
    return Reflect.get(getClient(), prop, receiver);
  },
});
